# Subsetting "zoo" objects

```{r}
options(jupyter.rich_display=FALSE) # Create output as usual in R
```

The following makes use of the *zoo* package. You may need to install it from
[CRAN](https://cran.r-project.org/package=zoo) using the code
`install.packages("zoo")` if you want to run this on your computer. (The
package is already installed on the notebook container, however.)

```{r}
library(zoo)
```

```{r}
as.yearqtr("1945 Q2")
```

The file "zpresidents.RData" was created in an earlier example.

```{r}
load("zpresidents.RData")
```

```{r}
zpresidents[as.yearqtr("1945 Q2")]
```

```{r}
qtrs3 <- as.yearqtr(paste(1960:1969,"Q3"))
zpresidents[qtrs3]
```

```{r}
qtrs <- paste(rep(1960:1964,each=4),rep(4:1,4),sep="-")
qtrs
```

```{r}
zpresidents[as.yearqtr(qtrs)]
```

```{r}
load("unemployment-z.RData")
```

```{r}
unemployment.z[as.Date("1997-12-31")]
```

```{r}
window(zpresidents,
       start = as.yearqtr("1969-1"),
       end   = as.yearqtr("1974-2"))
```

```{r}
window(unemployment.z,
       start = as.Date("1980-12-31"),
       end   = as.Date("1989-12-31"))
```
