channels:
  - conda-forge
dependencies:
  - gcc_impl_linux-64
  - gxx_impl_linux-64
  - r-base=3.6
  - r-data.table
  - r-haven
  - r-dplyr
  - r-readr
  - r-tidyr
  - r-survey
  - r-zoo
  - r-sf
  - r-sp
  - r-units
  - r-lwgeom
  - r-tm
  - r-quanteda
  - r-readtext
  - r-plyr
  - r-maptools
  - r-foreign
  - r-lattice
  - r-mass


